### ISSUE TITLE
[betterstats-2.8+1.19.4] Crash on startup

### ISSUE THREAD

**Issue by SteveKunG** [TheCSMods/mc-better-stats#54]
**Describe the bug**
When starting the game with latest version of the mod. Minecraft crashed instantly on startup.

**Log**
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'betterstats'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: io/github/thecsdev/tcdcommons/api/client/gui/screen/TScreenPlus
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.ClassNotFoundException: io.github.thecsdev.tcdcommons.api.client.gui.screen.TScreenPlus
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 more
```

**To Reproduce**
1. Simply download `betterstats-2.8+1.19.4` and install.
2. Run the game
3. Game crashed on startup.

**Expected behavior**
Game should be running.

**Comment by TheCSDev** [comment]
Hmm, that is a very odd error message. I just tested the mod, and yeah, it really does show up.
The reason this is odd and unexpected is because the error message implies the `tcdcommons` mod is missing. Thing is, `tcdcommons` is supposed to be embedded into `betterstats`, and automatically loaded as needed, but this doesn't seem to happen. For some reason Fabric loader is not loading `tcdcommons`.

Please download `tcdcommons` [from here](https://legacy.curseforge.com/projects/711539) while I work on resolving this issue.
If you get further crashes about `Fabric API` or `Architectury API`, then install those as well,
Thanks again for pointing it out, as I never even expected that to take place.
